##### Sales
* assumes that delivery orders are taken by e-commerce
* time series
* all sales
* daily change in sales

In [1]:
import polars as pl

In [2]:
import os

datafiles = os.listdir("../data")
datafiles

['sellers.csv',
 'products.csv',
 'customers.csv',
 'order_items.csv',
 'category_name_translation.csv',
 'order_reviews.csv',
 'geolocation.csv',
 'payments.csv',
 'schema.png',
 'orders.csv']

In [3]:
orders = pl.read_csv(source = "../data/orders.csv",
                    schema_overrides = {"order_purchase_timestamp": pl.Datetime,
                                        "order_approved_at": pl.Datetime,
                                        "order_delivered_carrier_date": pl.Datetime,
                                        "order_delivered_customer_date": pl.Datetime,
                                        "order_estimated_delivery_date": pl.Datetime})
orders

shape: (99_441, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ order_id   ┆ customer_i ┆ order_stat ┆ order_pur ┆ order_app ┆ order_del ┆ order_del ┆ order_est │
│ ---        ┆ d          ┆ us         ┆ chase_tim ┆ roved_at  ┆ ivered_ca ┆ ivered_cu ┆ imated_de │
│ str        ┆ ---        ┆ ---        ┆ estamp    ┆ ---       ┆ rrier_dat ┆ stomer_da ┆ livery_da │
│            ┆ str        ┆ str        ┆ ---       ┆ datetime[ ┆ e         ┆ te        ┆ te        │
│            ┆            ┆            ┆ datetime[ ┆ μs]       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆            ┆ μs]       ┆           ┆ datetime[ ┆ datetime[ ┆ datetime[ │
│            ┆            ┆            ┆           ┆           ┆ μs]       ┆ μs]       ┆ μs]       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ e481f51cbd ┆ 9ef432eb62 ┆ delivered  ┆ 2017-10-0 ┆ 2017-10-0 ┆ 2017-10-0 ┆ 2017-10-1 ┆ 2017-10-1 │
│ c54678b7cc ┆ 51297304e7 ┆            ┆ 2         ┆ 2         ┆ 4         ┆ 0         ┆ 8         │
│ 49136f2d6a ┆ 6186b10a92 ┆            ┆ 10:56:33  ┆ 11:07:15  ┆ 19:55:00  ┆ 21:25:13  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ 53cdb2fc8b ┆ b0830fb474 ┆ delivered  ┆ 2018-07-2 ┆ 2018-07-2 ┆ 2018-07-2 ┆ 2018-08-0 ┆ 2018-08-1 │
│ c7dce0b674 ┆ 7a6c6d20de ┆            ┆ 4         ┆ 6         ┆ 6         ┆ 7         ┆ 3         │
│ 1e21502734 ┆ a0b8c802d7 ┆            ┆ 20:41:37  ┆ 03:24:27  ┆ 14:31:00  ┆ 15:27:45  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ 47770eb910 ┆ 41ce2a54c0 ┆ delivered  ┆ 2018-08-0 ┆ 2018-08-0 ┆ 2018-08-0 ┆ 2018-08-1 ┆ 2018-09-0 │
│ 0c2d0c4494 ┆ b03bf3443c ┆            ┆ 8         ┆ 8         ┆ 8         ┆ 7         ┆ 4         │
│ 6d9cf07ec6 ┆ 3d931a3670 ┆            ┆ 08:38:49  ┆ 08:55:23  ┆ 13:50:00  ┆ 18:06:29  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ 949d5b44db ┆ f88197465e ┆ delivered  ┆ 2017-11-1 ┆ 2017-11-1 ┆ 2017-11-2 ┆ 2017-12-0 ┆ 2017-12-1 │
│ f5de918fe9 ┆ a7920adcdb ┆            ┆ 8         ┆ 8         ┆ 2         ┆ 2         ┆ 5         │
│ c16f97b45f ┆ ec7375364d ┆            ┆ 19:28:06  ┆ 19:45:59  ┆ 13:39:59  ┆ 00:28:42  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ ad21c59c08 ┆ 8ab97904e6 ┆ delivered  ┆ 2018-02-1 ┆ 2018-02-1 ┆ 2018-02-1 ┆ 2018-02-1 ┆ 2018-02-2 │
│ 40e6cb83a9 ┆ daea8866db ┆            ┆ 3         ┆ 3         ┆ 4         ┆ 6         ┆ 6         │
│ ceb5573f81 ┆ dbc4fb7aad ┆            ┆ 21:18:39  ┆ 22:20:29  ┆ 19:46:34  ┆ 18:17:02  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ 9c5dedf39a ┆ 39bd1228ee ┆ delivered  ┆ 2017-03-0 ┆ 2017-03-0 ┆ 2017-03-1 ┆ 2017-03-1 ┆ 2017-03-2 │
│ 927c1b2549 ┆ 8140590ac3 ┆            ┆ 9         ┆ 9         ┆ 0         ┆ 7         ┆ 8         │
│ 525ed64a05 ┆ aca26f2dfe ┆            ┆ 09:54:05  ┆ 09:54:05  ┆ 11:18:03  ┆ 15:08:01  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ 63943bddc2 ┆ 1fca14ff28 ┆ delivered  ┆ 2018-02-0 ┆ 2018-02-0 ┆ 2018-02-0 ┆ 2018-02-2 ┆ 2018-03-0 │
│ 61676b46f0 ┆ 61355f6e5f ┆            ┆ 6         ┆ 6         ┆ 7         ┆ 8         ┆ 2         │
│ 1ca7ac2f7b ┆ 14306ff977 ┆            ┆ 12:58:58  ┆ 13:10:37  ┆ 23:22:42  ┆ 17:37:56  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ 83c1379a01 ┆ 1aa71eb042 ┆ delivered  ┆ 2017-08-2 ┆ 2017-08-2 ┆ 2017-08-2 ┆ 2017-09-2 ┆ 2017-09-2 │
│ 5df1e13d02 ┆ 121263aafb ┆            ┆ 7         ┆ 7         ┆ 8         ┆ 1         ┆ 7         │
│ aae0204711 ┆ e80c1b562c ┆            ┆ 14:46:43  ┆ 15:04:16  ┆ 20:52:26  ┆ 11:24:17  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ 11c177c8e9 ┆ b331b74b18 ┆ delivered  ┆ 2018-01-0 ┆ 2018-01-0 ┆ 2018-01-1 ┆ 2018-01-2 ┆ 2018-02-1 │
│ 7725db2631 ┆ dc79bcdf65 ┆            ┆ 8         ┆ 8         ┆ 2         ┆ 5         ┆ 5         │
│ 073c19f07b ┆ 32d51e1637 ┆            ┆ 21:28:27  ┆ 21:36:21  ┆ 15:35:03  ┆ 23:32:54  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
│ 66dea50a8b ┆ edb027a75a ┆ delivered  ┆ 2018-03-0 ┆ 2018-03-0 ┆ 2018-03-0 ┆ 2018-03-1 ┆ 2018-04-0 │
│ 16d9b4dee7 ┆ 1449115f6b ┆            ┆ 8         ┆ 9         ┆ 9         ┆ 6         ┆ 3         │
│ af250b4be1 ┆ 43211ae02a ┆            ┆ 20:57:30  ┆ 11:20:28  ┆ 22:11:59  ┆ 13:08:30  ┆ 00:00:00  │
│ …          ┆ …          ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [4]:
items = pl.read_csv("../data/order_items.csv",
                    schema_overrides = {"shipping_limit_date": pl.Datetime})

In [5]:
items

shape: (112_650, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬────────┬──────────────┐
│ order_id     ┆ order_item_i ┆ product_id   ┆ seller_id    ┆ shipping_lim ┆ price  ┆ freight_valu │
│ ---          ┆ d            ┆ ---          ┆ ---          ┆ it_date      ┆ ---    ┆ e            │
│ str          ┆ ---          ┆ str          ┆ str          ┆ ---          ┆ f64    ┆ ---          │
│              ┆ i64          ┆              ┆              ┆ datetime[μs] ┆        ┆ f64          │
╞══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪════════╪══════════════╡
│ 00010242fe8c ┆ 1            ┆ 4244733e06e7 ┆ 48436dade18a ┆ 2017-09-19   ┆ 58.9   ┆ 13.29        │
│ 5a6d1ba2dd79 ┆              ┆ ecb4970a6e26 ┆ c8b2bce089ec ┆ 09:45:35     ┆        ┆              │
│ 2cb162…      ┆              ┆ 83c13e…      ┆ 2a0412…      ┆              ┆        ┆              │
│ 00018f77f2f0 ┆ 1            ┆ e5f2d52b8021 ┆ dd7ddc04e1b6 ┆ 2017-05-03   ┆ 239.9  ┆ 19.93        │
│ 320c557190d7 ┆              ┆ 89ee658865ca ┆ c2c614352b38 ┆ 11:05:13     ┆        ┆              │
│ a144bd…      ┆              ┆ 93d83a…      ┆ 3efe2d…      ┆              ┆        ┆              │
│ 000229ec3982 ┆ 1            ┆ c777355d18b7 ┆ 5b51032eddd2 ┆ 2018-01-18   ┆ 199.0  ┆ 17.87        │
│ 24ef6ca0657d ┆              ┆ 2b67abbeef9d ┆ 42adc84c38ac ┆ 14:48:30     ┆        ┆              │
│ a4fc70…      ┆              ┆ f44fd0…      ┆ ab88f2…      ┆              ┆        ┆              │
│ 00024acbcdf0 ┆ 1            ┆ 7634da152a46 ┆ 9d7a1d34a505 ┆ 2018-08-15   ┆ 12.99  ┆ 12.79        │
│ a6daa1e931b0 ┆              ┆ 10f1595efa32 ┆ 240900642527 ┆ 10:10:18     ┆        ┆              │
│ 38114c…      ┆              ┆ f14722…      ┆ 5ba1c2…      ┆              ┆        ┆              │
│ 00042b26cf59 ┆ 1            ┆ ac6c3623068f ┆ df560393f3a5 ┆ 2017-02-13   ┆ 199.9  ┆ 18.14        │
│ d7ce69dfabb4 ┆              ┆ 30de03045865 ┆ 1e74553ab940 ┆ 13:57:51     ┆        ┆              │
│ e55b4f…      ┆              ┆ e4e100…      ┆ 04ba5c…      ┆              ┆        ┆              │
│ …            ┆ …            ┆ …            ┆ …            ┆ …            ┆ …      ┆ …            │
│ fffc94f6ce00 ┆ 1            ┆ 4aa6014eceb6 ┆ b8bc237ba378 ┆ 2018-05-02   ┆ 299.99 ┆ 43.41        │
│ a00581880bf5 ┆              ┆ 82077f9dc4bf ┆ 8b23da09c0f1 ┆ 04:11:01     ┆        ┆              │
│ 4a75a0…      ┆              ┆ febc05…      ┆ f3a328…      ┆              ┆        ┆              │
│ fffcd46ef226 ┆ 1            ┆ 32e07fd91582 ┆ f3c38ab65283 ┆ 2018-07-20   ┆ 350.0  ┆ 36.53        │
│ 3f404302a634 ┆              ┆ 2b0765e448c4 ┆ 6d21de61fb83 ┆ 04:31:48     ┆        ┆              │
│ eb57f7…      ┆              ┆ dd74c8…      ┆ 14b691…      ┆              ┆        ┆              │
│ fffce4705a96 ┆ 1            ┆ 72a30483855e ┆ c3cfdc648177 ┆ 2017-10-30   ┆ 99.9   ┆ 16.95        │
│ 62cd70adb13d ┆              ┆ 2eafc67aee5d ┆ fdbbbb35635a ┆ 17:14:25     ┆        ┆              │
│ 4a3183…      ┆              ┆ c25604…      ┆ 37472c…      ┆              ┆        ┆              │
│ fffe18544ffa ┆ 1            ┆ 9c422a519119 ┆ 2b3e4a2a3ea8 ┆ 2017-08-21   ┆ 55.99  ┆ 8.72         │
│ bc95dfada217 ┆              ┆ dcad7575db5a ┆ e01938cabda2 ┆ 00:04:32     ┆        ┆              │
│ 79c964…      ┆              ┆ f1ba54…      ┆ a3e5cc…      ┆              ┆        ┆              │
│ fffe41c64501 ┆ 1            ┆ 350688d9dc1e ┆ f7ccf836d21b ┆ 2018-06-12   ┆ 43.0   ┆ 12.79        │
│ cc87c801fd61 ┆              ┆ 75ff97be3263 ┆ 2fb1de375641 ┆ 17:10:13     ┆        ┆              │
│ db3f62…      ┆              ┆ 63655e…      ┆ 05216c…      ┆              ┆        ┆              │
└──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴────────┴──────────────┘

In [9]:
sales = items.join(orders,
          on = "order_id",
          how = "left")
sales = sales.with_columns(
    pl.col("order_purchase_timestamp").dt.month().alias("month"),
    pl.col("order_purchase_timestamp").dt.year().alias("year")
)
monthly_sales = sales.group_by(["year", "month"]).agg(pl.col("freight_value").sum().alias("sales")).sort(["year", "month"])

In [7]:
monthly_sales = monthly_sales.with_columns(pl.col("sales").diff().alias("growth"))
monthly_sales = monthly_sales.with_columns(pl.col("sales").diff(n=12).alias("y_y_change"))

In [17]:
monthly_sales.with_columns(pl.date(2018, pl.col("month"), 1).dt.strftime("%B").alias("month"))

shape: (24, 3)
┌──────┬───────────┬───────────┐
│ year ┆ month     ┆ sales     │
│ ---  ┆ ---       ┆ ---       │
│ i32  ┆ str       ┆ f64       │
╞══════╪═══════════╪═══════════╡
│ 2016 ┆ September ┆ 87.39     │
│ 2016 ┆ October   ┆ 7301.18   │
│ 2016 ┆ December  ┆ 8.72      │
│ 2017 ┆ January   ┆ 16875.62  │
│ 2017 ┆ February  ┆ 38977.6   │
│ …    ┆ …         ┆ …         │
│ 2018 ┆ May       ┆ 153264.14 │
│ 2018 ┆ June      ┆ 157552.8  │
│ 2018 ┆ July      ┆ 163220.81 │
│ 2018 ┆ August    ┆ 148622.14 │
│ 2018 ┆ September ┆ 21.46     │
└──────┴───────────┴───────────┘